openapi: "3.0.0"
info:
  title: Movie Seat Selection API
  description: API for retrieving available seats for a specific movie, reserving them, and canceling reservations.
  version: "1.0.0"

paths:
  /seats:
    get:
      summary: Retrieve available seats
      description: Provides a list of available seats for a specified movie and show time.
      parameters:
        - in: query
          name: movie_id
          required: true
          schema:
            type: string
          description: The unique identifier of the movie.
        - in: query
          name: show_time
          required: true
          schema:
            type: string
          description: The time of the movie showing (format: HH:MM).
      responses:
        '200':
          description: A list of available seats
          ...
        '400':
          description: Bad Request - Invalid movie ID or show time format
          ...
        '404':
          description: Not Found - Movie or show time not found
          ...

  /seats/reserve:
    post:
      summary: Reserve seats for a movie
      description: This endpoint allows users to reserve specific seats for a movie.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movie_id:
                  type: string
                  description: Unique identifier for the movie.
                show_time:
                  type: string
                  description: The time of the movie showing.
                seats:
                  type: array
                  items:
                    type: string
                  description: List of seats to reserve.
      responses:
        '201':
          description: Seats reserved successfully
        '400':
          description: Bad Request - Invalid seat selection or parameters
        '409':
          description: Conflict - Seat already reserved

  /seats/reservation/{reservation_id}:
    delete:
      summary: Cancel a seat reservation
      description: Allows a user to cancel an existing reservation.
      parameters:
        - in: path
          name: reservation_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reservation canceled successfully
        '404':
          description: Not Found - Reservation ID not found
        '500':
          description: Server error while canceling reservation
